name: flutter_mcp_server
description: MCP server exposing tools for Flutter projects.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  dart_mcp: ^0.5.2
  analyzer: ^14.1.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
